spring:
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gsy-goods-cloud
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: yourpassword
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8     # 最大活跃连接数
          max-idle: 8       # 最大空闲连接数
          min-idle: 0       # 最小空闲连接数
          max-wait: -1ms    # 获取连接的最大等待时间（-1 表示无限制）
    mongodb:
      uri: mongodb://127.0.0.1:27017/gsy-goods-cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  codec:
    max-in-memory-size: 100MB