<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanshiyun</groupId>
        <artifactId>guanshiyun</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>gsy-order-cloud</artifactId>
    <packaging>pom</packaging>

    <name>gsy-order-cloud</name>
    <url>http://maven.apache.org</url>
    <modules>
        <module>order-app</module>
        <module>order-server</module>
        <module>order-pojo</module>
        <module>order-common-utils</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <snapshotName>0.0.1-SNAPSHOT</snapshotName>
        <loadbalancer.version>4.2.1</loadbalancer.version>
        <junit.version>4.13.2</junit.version>
        <r2dbc.mysql.version>1.4.1</r2dbc.mysql.version>
        <mysql.version>8.4.0</mysql.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>goods-server-api</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>public-pojo-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>microservice-security-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>db-table-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>order-server-api</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-r2dbc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>io.asyncer</groupId>
            <artifactId>r2dbc-mysql</artifactId>
            <version>${r2dbc.mysql.version}</version>
        </dependency>
        <!-- H2 Database (for dev) -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- R2DBC Driver for H2 -->
        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>common-utils-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
    </dependencies>
</project>
