spring:
  application:
    name: system-app
  profiles:
    active: dev,middleware
server:
  port: 9527

logging:
  level:
    root: INFO
    io.r2dbc.spi: DEBUG           # R2DBC SPI 层日志
    org.springframework.r2dbc.core: DEBUG   # Spring R2DBC 核心模板日志
    org.springframework.r2dbc.connection: DEBUG
    io.r2dbc.mysql: DEBUG
    io.r2dbc.pool: DEBUG
    com.alibaba.nacos.client: DEBUG




