<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanshiyun</groupId>
        <artifactId>guanshiyun</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath> ../pom.xml</relativePath>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>ai-pojo</module>
        <module>ai-server</module>
        <module>ai-app</module>
        <module>ai-common-util</module>
    </modules>
    <artifactId>gsy-ai-cloud</artifactId>
    <name>gsy-ai-cloud</name>
    <description>gsy-ai-cloud</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>

    <dependencies>

        <!-- Source: https://mvnrepository.com/artifact/ai.djl/api -->
        <dependency>
            <groupId>ai.djl</groupId>
            <artifactId>api</artifactId>
            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-engine -->
        <dependency>
            <groupId>ai.djl.pytorch</groupId>
            <artifactId>pytorch-engine</artifactId>

            <scope>compile</scope>
        </dependency>
        <!-- Source: https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cu121 -->
<!--        <dependency>-->
<!--            <groupId>ai.djl.pytorch</groupId>-->
<!--            <artifactId>pytorch-native-cu121</artifactId>-->
<!--            <version>2.3.1</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
        <!-- Source: https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-model-zoo -->
<!--        <dependency>-->
<!--            <groupId>ai.djl.pytorch</groupId>-->
<!--            <artifactId>pytorch-model-zoo</artifactId>-->
<!--            <version>0.36.0</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
        <!-- Source: https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-jni -->
<!--        <dependency>-->
<!--            <groupId>ai.djl.pytorch</groupId>-->
<!--            <artifactId>pytorch-jni</artifactId>-->
<!--            <version>2.7.1-0.36.0</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Source: https://mvnrepository.com/artifact/ai.djl.pytorch/pytorch-native-cu124 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>ai.djl.pytorch</groupId>-->
<!--            <artifactId>pytorch-native-cu124</artifactId>-->
<!--            <version>2.5.1</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>dashscope-sdk-java</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
                <!-- 可选：如果它还带了 slf4j-api 重复，也可排除（但通常不需要） -->
                <!-- <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-api</artifactId>
                </exclusion> -->
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
        </dependency>

        <!-- 【关键】WebFlux 专用适配器，替代 sentinel-web-servlet -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-spring-webflux-adapter</artifactId>

        </dependency>
        <!-- 规则持久化依赖 -->
        <dependency>
            <groupId>com.alibaba.csp</groupId>
            <artifactId>sentinel-datasource-nacos</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>io.modelcontextprotocol.sdk</groupId>-->
<!--            <artifactId>mcp</artifactId>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; 基于 Spring WebFlux 的 SSE 客户端和服务器传输 &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>io.modelcontextprotocol.sdk</groupId>-->
<!--            <artifactId>mcp-spring-webflux</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>io.qdrant</groupId>-->
<!--            <artifactId>client</artifactId>-->
<!--        </dependency>-->
        <!-- Source: https://mvnrepository.com/artifact/com.github.victools/jsonschema-generator -->
        <dependency>
            <groupId>com.github.victools</groupId>
            <artifactId>jsonschema-generator</artifactId>
            <version>4.38.0</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.github.victools</groupId>
            <artifactId>jsonschema-module-jackson</artifactId>
            <version>4.38.0</version>
            <scope>compile</scope>
        </dependency>
        <!-- Spring AI Alibaba Agent Framework -->
<!--        <dependency>-->
<!--            <groupId>com.alibaba.cloud.ai</groupId>-->
<!--            <artifactId>spring-ai-alibaba-agent-framework</artifactId>-->
<!--            <version>${spring-alibaba-ai.version}</version>-->
<!--        </dependency>-->

        <!-- DashScope ChatModel 支持（如果使用其他模型，请跳转 Spring AI 文档选择对应的 starter） -->
        <dependency>
            <groupId>com.alibaba.cloud.ai</groupId>
            <artifactId>spring-ai-alibaba-starter-dashscope</artifactId>
            <version>${spring-alibaba-ai.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-vector-store-qdrant</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-advisors-vector-store</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>behavior-server-api</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>microservice-security-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>db-table-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>redis-utils-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>

        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>common-utils-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>public-pojo-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-r2dbc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.asyncer</groupId>
            <artifactId>r2dbc-mysql</artifactId>
        </dependency>
        <!-- H2 Database (for dev) -->
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>runtime</scope>
        </dependency>

        <!-- R2DBC Driver for H2 -->
        <dependency>
            <groupId>io.r2dbc</groupId>
            <artifactId>r2dbc-h2</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-mongodb-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-starter-model-ollama</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-client-chat</artifactId>
        </dependency>

        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>ai-server-api</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>goods-server-api</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>r2dbc-postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-autoconfigure-model-chat-client</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.springframework.ai</groupId>-->
<!--            <artifactId>spring-ai-autoconfigure-model-chat-client</artifactId>-->
<!--            <version>${spring-ai.version}</version>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-autoconfigure-model-embedding-observation</artifactId>
<!--            <version>${spring-ai.version}</version>-->
        </dependency>
        <dependency>
            <groupId>org.springframework.ai</groupId>
            <artifactId>spring-ai-autoconfigure-model-chat-memory</artifactId>
<!--            <version>${spring-ai.version}</version>-->
        </dependency>
        <!-- https://mvnrepository.com/artifact/org.springframework.ai/spring-ai-starter-mcp-server -->
<!--        <dependency>-->
<!--            <groupId>org.springframework.ai</groupId>-->
<!--            <artifactId>spring-ai-starter-mcp-server</artifactId>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.aliyun</groupId>-->
<!--            <artifactId>aliyun-java-sdk-core</artifactId>-->
<!--            <version>${aliyun.core.version}</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
