spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: gpt-oss:20b
#           model: qwen3:latest
#          model: qwen2.5:7b
      embedding:
        options:
          model: dengcao/Qwen3-Embedding-4B:Q4_K_M
#          model: dengcao/Qwen3-Embedding-8B:Q4_K_M
    vectorstore:
      qdrant:
        host: 127.0.0.1
        port: 6334
        api-key: qdrant-api-key
        collection-name: gsy-embedding-cloud
        use-tls: false
        initialize-schema: true
