spring:
#  qdrant:
#    rest-api: http://127.0.0.1:6333  # Qdrant 服务的地址
#    grpc-api: http://127.0.0.1:6334
#    api-key: qdrant-api-key
  r2dbc:
    mysql:
      url: r2dbc:mysql://127.0.0.1:3306/gsy-ai-cloud
      username: root
      password: 1234
    postgres:
      url: r2dbc:postgresql://127.0.0.1:5432/gsy-embedding-cloud
      username: postgres
      password: 123456
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #      password: yourpassword
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8     # 最大活跃连接数
          max-idle: 8       # 最大空闲连接数
          min-idle: 0       # 最小空闲连接数
          max-wait: -1ms    # 获取连接的最大等待时间（-1 表示无限制）
    mongodb:
      primary:
        uri: mongodb://127.0.0.1:27017
        database: gsy-ai-cloud
      secondary:
        uri: mongodb://127.0.0.1:27017
#      username:
#      password:
        database: gsy-embedding-cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  webflux:
    multipart:
      max-in-memory-size: 1024MB
  output:
    ansi:
      enabled: ALWAYS