spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      eager: true

      datasource:
        ds-authority:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr} # 建议引用上方配置，避免硬编码
            namespace: ${spring.cloud.nacos.discovery.namespace}
            data-id: ${spring.application.name}-authority-rules
            group-id: DEFAULT_GROUP
            rule-type: authority
            data-type: json
        ds-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            namespace: ${spring.cloud.nacos.discovery.namespace} # 【必须添加】同上
            data-id: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
      enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gsy-goods-cloud
    username: root
    password: 1234
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8     # 最大活跃连接数
          max-idle: 8       # 最大空闲连接数
          min-idle: 0       # 最小空闲连接数
          max-wait: -1ms    # 获取连接的最大等待时间（-1 表示无限制）
    mongodb:
      uri: mongodb://127.0.0.1:27017/gsy-goods-cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  webflux:
    multipart:
      max-in-memory-size: 100MB
      ########### powerjob-worker 配置 ###########

powerjob:
  worker:
    # akka 工作端口，可选，默认 27777
    port: 27777
    # 接入应用名称，用于分组隔离，推荐填写 本 Java 项目名称
    app-name: gsy-goods-cloud
    # 调度服务器地址，IP:Port 或 域名，多值逗号分隔
    server-address: 127.0.0.1:7700
    # 持久化方式，可选，默认 disk
    store-strategy: disk
    # 任务返回结果信息的最大长度，超过这个长度的信息会被截断，默认 8192
    max-result-length: 8192
    # 单个任务追加的工作流上下文最大长度，超过这个长度的会被直接丢弃，默认 8192
    max-appended-wf-context-length: 8192
    #开发环境置为false
    enabled: false
    # 是否开启任务日志，默认 false
#    tag: true
gorse:
  url: 127.0.0.1:8087
  api-key: api-key

server:
  port: 9533

logging:
  level:
    root: info
    io.r2dbc.spi: debug           # R2DBC SPI 层日志
    org.springframework.r2dbc.core: debug   # Spring R2DBC 核心模板日志
    com.zaxxer.r2dbc: debug       # 如果使用 HikariR2DBC（不常见）
    com.alibaba.nacos.client: debug