spring:
  application:
    name: sys-department-app # 应用程序的名称，用于标识该 Spring Boot 应用。
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: dev
    include:
      - mail
      - oss
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  webflux:
    multipart:
      max-in-memory-size: 100MB
  http:
    codecs:
      max-in-memory-size: 100MB

