<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanshiyun</groupId>
        <artifactId>gsy-behavior-cloud</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>behavior-pojo</artifactId>
    <packaging>jar</packaging>

    <name>behavior-pojo</name>
    <url>http://maven.apache.org</url>
    <version>${snapshotName}</version>

    <dependencies>
    </dependencies>
    <build>
        <plugins>
            <!-- 覆盖父工程的配置，跳过 repackage -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
