<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.guanshiyun</groupId>
		<artifactId>common-utils-cloud</artifactId>
		<version>0.0.1-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>aliyun-oss-spring-boot-autoconfigure</artifactId>
	<name>aliyun-oss-spring-boot-autoconfigure</name>
	<description>aliyun-oss-spring-boot-autoconfigure</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
	</properties>
	<dependencies>
		<!--引入aliyun,jwt令牌依赖-->
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-api</artifactId>
			<version>${jjwt-impl.version}</version>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-impl</artifactId>
			<version>${jjwt-impl.version}</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>io.jsonwebtoken</groupId>
			<artifactId>jjwt-jackson</artifactId> <!-- or jjwt-gson if Gson is preferred -->
			<version>${jjwt-impl.version}</version>
			<scope>runtime</scope>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>javax.xml.bind</groupId>-->
<!--			<artifactId>jaxb-api</artifactId>-->
<!--			<version>${jaxbapi.version}</version>-->
<!--		</dependency>-->
<!--		<dependency>-->
<!--			<groupId>javax.activation</groupId>-->
<!--			<artifactId>activation</artifactId>-->
<!--			<version>${jafx.version}</version>-->
<!--		</dependency>-->
		<!-- no more than 2.3.3-->
<!--		<dependency>-->
<!--			<groupId>org.glassfish.jaxb</groupId>-->
<!--			<artifactId>jaxb-runtime</artifactId>-->
<!--			<version>${jaxbr.version}</version>-->
<!--		</dependency>-->
		<!--
		aliyun oss依赖
		-->

<!--		<dependency>-->
<!--			<groupId>com.aliyun.oss</groupId>-->
<!--			<artifactId>aliyun-sdk-oss</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>com.aliyun</groupId>
			<artifactId>alibabacloud-oss-v2</artifactId>
		</dependency>
		<dependency>
			<groupId>com.aliyun</groupId>
			<artifactId>alibabacloud-dysmsapi20180501</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-mail</artifactId>
		</dependency>
<!--		<dependency>-->
<!--			<groupId>com.alibaba.fastjson2</groupId>-->
<!--			<artifactId>fastjson2</artifactId>-->
<!--		</dependency>-->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
		</dependency>
	</dependencies>

</project>
