spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: dev
    sentinel:
      transport:
        dashboard: localhost:8888
        port: 8719
      eager: true

      datasource:
        ds-authority:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr} # 建议引用上方配置，避免硬编码
            namespace: ${spring.cloud.nacos.discovery.namespace}
            data-id: ${spring.application.name}-authority-rules
            group-id: DEFAULT_GROUP
            rule-type: authority
            data-type: json
        ds-flow:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            namespace: ${spring.cloud.nacos.discovery.namespace} # 【必须添加】同上
            data-id: ${spring.application.name}-flow-rules
            group-id: DEFAULT_GROUP
            rule-type: flow
            data-type: json
      enabled: false
  r2dbc:
    url: r2dbc:mysql://localhost:3306/gsy-sys-cloud
    username: root
    password: 1234
    pool:
      enabled: true                 # 显式开启连接池（Spring Boot 3通常默认开启，写上更稳妥）
      initial-size: 20              # 应用启动时预先创建好的空闲连接数（避免冷启动时临时建连接耗时）
      max-size: 150                 # 【最关键】最大连接数！默认通常只有10，根据你的压测需求建议调到50~100
      max-idle-time: 30m            # 连接的最大空闲时间，超过这个时间没被使用就会被释放
      max-life-time: 60m            # 连接的最大存活时间，防止长连接在数据库端异常断开
      max-acquire-time: 10s         # 获取连接的最大等待超时时间（配合你的压测代码，防止请求无限卡死）
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: 123456
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 50    # 最大活跃连接数
          max-idle: 20       # 最大空闲连接数
          min-idle: 5       # 最小空闲连接数
          max-wait: 2000ms    # 获取连接的最大等待时间（-1 表示无限制）
    mongodb:
      uri: mongodb://127.0.0.1:27017/gsy-sys-cloud
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false

server:
  port: 9527

logging:
  level:
    root: info
    io.r2dbc.spi: info          # R2DBC SPI 层日志
    org.springframework.r2dbc.core: info   # Spring R2DBC 核心模板日志
    org.springframework.r2dbc.connection: info
    io.r2dbc.mysql: info
    io.r2dbc.pool: info
    com.alibaba.nacos.client: info

gorse:
  url: 127.0.0.1:8087
  api-key: api-key