<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.guanshiyun</groupId>
        <artifactId>guanshiyun</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <packaging>pom</packaging>
    <modules>
        <module>ai-server-api</module>
        <module>recommend-server-api</module>
        <module>statistical-server-api</module>
        <module>sys-server-api</module>
        <module>goods-server-api</module>
        <module>behavior-server-api</module>
        <module>order-server-api</module>
        <module>upload-server-api</module>
    </modules>
    <artifactId>gsy-general-api-cloud</artifactId>
    <name>gsy-general-api-cloud</name>
    <description>gsy-general-api-cloud</description>
    <url/>
    <licenses>
        <license/>
    </licenses>
    <developers>
        <developer/>
    </developers>
    <scm>
        <connection/>
        <developerConnection/>
        <tag/>
        <url/>
    </scm>
    <properties>
<!--        <feign.version>4.2.1</feign.version>-->
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>web-client-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>common-utils-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
        <dependency>
            <groupId>com.guanshiyun</groupId>
            <artifactId>public-pojo-spring-boot-starter</artifactId>
            <version>${snapshotName}</version>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.springframework.cloud</groupId>-->
<!--            <artifactId>spring-cloud-starter-circuitbreaker-reactor-resilience4j</artifactId>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>com.playtika.reactivefeign</groupId>-->
<!--            <artifactId>feign-reactor-cloud</artifactId>-->
<!--            <version>${feign.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.playtika.reactivefeign</groupId>-->
<!--            <artifactId>feign-reactor-spring-configuration</artifactId>-->
<!--            <version>${feign.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>com.playtika.reactivefeign</groupId>-->
<!--            <artifactId>feign-reactor-webclient</artifactId>-->
<!--            <version>${feign.version}</version>-->
<!--        </dependency>-->
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
