spring:
  application:
    name: gateway-server-app
  profiles:
    active: data,middleware,app

server:
  port: 9528
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
#debug: true

